"""Step 2 — Render trigger.

Triggers the local Remotion project to render the motion-graphics video.

Pipeline flow:
  1. If VOICEOVER_MODE=auto, the voiceover MP3 is already generated by
     voiceover.py. In manual mode this step first PAUSES and waits for you to
     drop your kikivoice.ai export into the topic workspace.
  2. The voiceover is copied into the Remotion `public/audio/<slug>/` folder so
     the <Audio> element can play it (Remotion resolves staticFile from public/).
  3. Its duration is measured and written to src/episodeRuntime.json, which the
     "Episode" composition reads for its durationInFrames.
  4. `npm run render` is launched with the script (title/hook/sections/cta) and
     audio reference passed as --props.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

import config

# Must match INTRO / OUTRO in src/scenes/episode/Episode.tsx
INTRO_FRAMES = 75
OUTRO_FRAMES = 90
FPS = 30


def wait_for_audio(audio_path: Path) -> None:
    if audio_path.exists():
        print(f"[render] Audio already present: {audio_path}")
        return
    print(f"[render] Waiting for voiceover at: {audio_path}")
    print("[render] Upload your kikivoice.ai export there, then it continues.")
    waited = 0
    while not audio_path.exists():
        time.sleep(config.AUDIO_POLL_INTERVAL)
        waited += config.AUDIO_POLL_INTERVAL
        if config.AUDIO_WAIT_TIMEOUT and waited >= config.AUDIO_WAIT_TIMEOUT:
            raise TimeoutError(f"Timed out after {waited}s waiting for {audio_path}")
        if waited % 60 == 0:
            print(f"[render] ...still waiting ({waited}s)")
    print(f"[render] Audio detected: {audio_path}")


def _audio_frames(audio_path: Path) -> int:
    """Return audio length in frames (best effort)."""
    # Try ffprobe first.
    for exe in ("ffprobe", "avprobe"):
        try:
            out = subprocess.run(
                [exe, "-v", "error", "-show_entries", "format=duration",
                 "-of", "default=noprint_wrappers=1:nokey=1", str(audio_path)],
                capture_output=True, text=True, timeout=30,
            )
            secs = float(out.stdout.strip())
            return max(int(round(secs * FPS)), 1)
        except Exception:
            pass
    # Fallback: estimate from file size assuming ~48 kbps (typical Edge TTS).
    kbps = 48
    secs = (audio_path.stat().st_size * 8) / 1000 / kbps
    return max(int(round(secs * FPS)), 1)


def _copy_voiceover(audio_path: Path, slug: str) -> str:
    public_audio = config.REMOTION_PROJECT_DIR / "public" / "audio" / slug
    public_audio.mkdir(parents=True, exist_ok=True)
    dest = public_audio / "voiceover.mp3"
    shutil.copyfile(audio_path, dest)
    return f"audio/{slug}/voiceover.mp3"


def _write_runtime(slug: str, script: dict, audio_src: str, audio_frames: int) -> int:
    total = INTRO_FRAMES + audio_frames + OUTRO_FRAMES
    runtime = {
        "durationInFrames": total,
        "audioSrc": audio_src,
        "audioDurationInFrames": audio_frames,
        "title": script.get("title", slug),
        "hook": script.get("hook", ""),
        "sections": script.get("sections", []),
        "cta": script.get("cta", ""),
    }
    (config.REMOTION_PROJECT_DIR / "src" / "episodeRuntime.json").write_text(
        json.dumps(runtime, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return total


def render(topic_slug: str, audio_path: Path) -> Path:
    """Run the Remotion render and return the path to the output mp4."""
    ws = config.WORKSPACE / topic_slug
    script = json.loads((ws / config.SCRIPT_JSON_REL).read_text(encoding="utf-8"))

    audio_src = _copy_voiceover(audio_path, topic_slug)
    audio_frames = _audio_frames(audio_path)
    total = _write_runtime(topic_slug, script, audio_src, audio_frames)
    print(f"[render] Audio {audio_frames} frames (~{audio_frames/FPS:.0f}s); "
          f"total {total} frames (~{total/FPS:.0f}s)")

    out_name = f"{topic_slug}.mp4"
    out_path = config.REMOTION_OUT_DIR / out_name
    config.REMOTION_OUT_DIR.mkdir(parents=True, exist_ok=True)

    props = {
        "title": script.get("title", topic_slug),
        "hook": script.get("hook", ""),
        "sections": script.get("sections", []),
        "cta": script.get("cta", ""),
        "audioSrc": audio_src,
        "audioDurationInFrames": audio_frames,
    }

    cmd = [
        "npm", "run", "render", "--",
        config.REMOTION_COMPOSITION_ID,
        str(out_path),
        "--props", json.dumps(props),
    ]
    print(f"[render] Running: {' '.join(cmd)}")
    subprocess.run(cmd, cwd=str(config.REMOTION_PROJECT_DIR), check=True)
    if not out_path.exists():
        raise RuntimeError(f"Render finished but output missing: {out_path}")

    # Mux the voiceover into the silent render (reliable on headless Chromium).
    muxed = _mux_audio(out_path, audio_path)
    if muxed:
        out_path = muxed

    print(f"[render] Done: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Batch rendering (resumable, crash-safe) + preview mode
# ---------------------------------------------------------------------------
def _prepare(slug: str, audio_path: Path):
    """Shared prep: load script, copy audio, write runtime, build props."""
    ws = config.WORKSPACE / slug
    script = json.loads((ws / config.SCRIPT_JSON_REL).read_text(encoding="utf-8"))
    audio_src = _copy_voiceover(audio_path, slug)
    audio_frames = _audio_frames(audio_path)
    total = _write_runtime(slug, script, audio_src, audio_frames)
    props = {
        "title": script.get("title", slug),
        "hook": script.get("hook", ""),
        "sections": script.get("sections", []),
        "cta": script.get("cta", ""),
        "audioSrc": audio_src,
        "audioDurationInFrames": audio_frames,
    }
    return script, audio_frames, total, props


def _remotion_render_range(out_path: Path, props: dict, frm: int, to: int) -> None:
    cmd = [
        "npm", "run", "render", "--",
        config.REMOTION_COMPOSITION_ID, str(out_path),
        "--props", json.dumps(props),
        "--frames", f"{frm}-{to-1}",
    ]
    if config.REMOTION_BROWSER_EXECUTABLE:
        cmd += ["--browser-executable", str(config.REMOTION_BROWSER_EXECUTABLE)]
    print(f"[render] segment frames {frm}-{to}: {' '.join(cmd)}")
    subprocess.run(cmd, cwd=str(config.REMOTION_PROJECT_DIR), check=True)


def _concat_segments(segments: list[Path], out_path: Path) -> Path:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise RuntimeError("ffmpeg required to concatenate render segments")
    list_file = out_path.parent / "segments.txt"
    list_file.write_text(
        "\n".join(f"file '{p.resolve()}'" for p in segments), encoding="utf-8"
    )
    print(f"[render] Concatenating {len(segments)} segments -> {out_path.name}")
    subprocess.run(
        [ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", str(list_file),
         "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an", str(out_path)],
        check=True,
    )
    return out_path


def _slice_audio(audio_path: Path, start: float, duration: float) -> Path:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise RuntimeError("ffmpeg required to slice audio")
    out = config.REMOTION_OUT_DIR / "preview_slice.mp3"
    print(f"[render] Slicing audio 0-{duration:.0f}s for preview")
    subprocess.run(
        [ffmpeg, "-y", "-i", str(audio_path), "-ss", str(start),
         "-t", str(duration), "-c", "copy", str(out)], check=True,
    )
    return out


def _render_segments(slug: str, audio_path: Path, end_frame: int):
    """Render frame range [0, end_frame) as resumable batches; return seg list."""
    _, _, total, props = _prepare(slug, audio_path)
    end_frame = min(end_frame, total)
    seg_dir = config.REMOTION_OUT_DIR / "segments" / slug
    seg_dir.mkdir(parents=True, exist_ok=True)
    segments, frm, idx = [], 0, 0
    while frm < end_frame:
        to = min(frm + config.RENDER_BATCH_FRAMES, end_frame)
        seg = seg_dir / f"seg_{idx:03d}.mp4"
        if seg.exists() and seg.stat().st_size > 1000:
            print(f"[render] reuse segment {seg.name}")
        else:
            if seg.exists():
                seg.unlink()
            _remotion_render_range(seg, props, frm, to)
        segments.append(seg)
        frm, idx = to, idx + 1
    return segments


def render_preview(slug: str, audio_path: Path, seconds: float = 60) -> Path:
    """Render the first `seconds` of the episode (with audio) as a preview."""
    end_frame = int(seconds * FPS)
    print(f"[render] PREVIEW: first {seconds:.0f}s (~{end_frame} frames)")
    segments = _render_segments(slug, audio_path, end_frame)
    silent = _concat_segments(
        segments, config.REMOTION_OUT_DIR / f"{slug}_preview_silent.mp4")
    sliced = _slice_audio(audio_path, 0, end_frame / FPS)
    final = _mux_audio(silent, sliced)
    print(f"[render] PREVIEW ready: {final}")
    return final


def render_batches(slug: str, audio_path: Path) -> Path:
    """Render the full episode in resumable batches, concatenate, mux audio."""
    _, _, total, _ = _prepare(slug, audio_path)
    print(f"[render] FULL BATCH render: {total} frames in "
          f"{config.RENDER_BATCH_FRAMES}-frame segments")
    segments = _render_segments(slug, audio_path, total)
    silent = _concat_segments(
        segments, config.REMOTION_OUT_DIR / f"{slug}_silent.mp4")
    final = _mux_audio(silent, audio_path)
    print(f"[render] FULL video ready: {final}")
    return final


def _mux_audio(silent_path: Path, audio_path: Path) -> Path | None:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        print("[render] ffmpeg not found; skipping audio mux (silent video).")
        return None
    final = silent_path.with_name(silent_path.stem + "_final.mp4")
    print(f"[render] Muxing voiceover via ffmpeg -> {final.name}")
    subprocess.run(
        [ffmpeg, "-y", "-i", str(silent_path), "-i", str(audio_path),
         "-c:v", "copy", "-c:a", "aac", "-shortest", str(final)],
        check=True,
    )
    silent_path.unlink()
    final.rename(silent_path)
    return silent_path


if __name__ == "__main__":
    slug = sys.argv[1] if len(sys.argv) > 1 else input("Topic slug: ")
    mode = sys.argv[2] if len(sys.argv) > 2 else "full"
    ap = config.WORKSPACE / slug / config.VOICEOVER_FILENAME
    wait_for_audio(ap)
    if mode == "preview":
        render_preview(slug, ap, seconds=60)
    elif mode == "batches":
        render_batches(slug, ap)
    else:
        render(slug, ap)
