#!/usr/bin/env python3
"""fetch_fonts.py — fetch Fontshare families and emit base64 @font-face CSS.

Downloads Melodrama / Switzer / Fragment Mono woff2 files and writes a
self-contained CSS file (src/styles/fontshare-fonts.css) with data-URI fonts,
so Remotion Studio renders them without dev-server asset fetches.
"""
import base64
import os
import re
import urllib.request

CSS_URL = (
    "https://api.fontshare.com/v2/css"
    "?f[]=melodrama@400,700"
    "&f[]=switzer@400,500,700"
    "&f[]=jet-brains-mono@400"
    "&display=swap"
)
OUT = "src/styles/fontshare-fonts.css"


def main():
    req = urllib.request.Request(CSS_URL, headers={"User-Agent": "Mozilla/5.0"})
    css = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")

    blocks = re.findall(r"@font-face\s*\{([^}]+)\}", css)
    rules = []
    for b in blocks:
        fam = re.search(r"font-family:\s*'([^']+)'", b)
        wt = re.search(r"font-weight:\s*(\d+)", b)
        url = re.search(r"src:\s*url\('(//[^']+\.woff2)'\)", b)
        if not (fam and wt and url):
            continue
        family = fam.group(1)
        weight = wt.group(1)
        src = "https:" + url.group(1)
        data = urllib.request.urlopen(src, timeout=60).read()
        b64 = base64.b64encode(data).decode("ascii")
        rules.append(
            "/* %s %s (%d KB) */\n"
            "@font-face {\n"
            "  font-family: '%s';\n"
            "  font-weight: %s;\n"
            "  font-style: normal;\n"
            "  font-display: swap;\n"
            "  src: url('data:font/woff2;base64,%s') format('woff2');\n"
            "}\n" % (family, weight, len(data) // 1024, family, weight, b64)
        )
        print("fetched %s %s (%d KB)" % (family, weight, len(data) // 1024))

    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by scripts/fetch_fonts.py — Fontshare fonts, base64-embedded. */\n")
        f.write("/* Melodrama (display), Switzer (body/grotesk), Fragment Mono (accent/mono). */\n\n")
        f.write("\n".join(rules))
    print("wrote %s (%d faces)" % (OUT, len(rules)))


if __name__ == "__main__":
    main()
