// Generates base64 data-URI constants for the small image assets used by the
// Part 1 scene. Remotion's headless `still` render in this environment does not
// serve `public/` files, so images must be inlined as data URIs to render.
// (The .webm/.mp4 footage still uses staticFile, since video only plays in a
// real browser/Studio anyway.)
const fs = require("fs");
const path = require("path");

const ROOT = process.cwd();
const files = {
  desktopSvg: "public/04_DEVICE_FRAMES/Desktop/desktop.svg",
  laptopSvg: "public/04_DEVICE_FRAMES/Laptops/laptop.svg",
  phoneSvg: "public/04_DEVICE_FRAMES/Phones/phone.svg",
  tabletSvg: "public/04_DEVICE_FRAMES/Tablets/tablet.svg",
  midjourney: "public/logos/midjourney_com.jpg",
  flux: "public/logos/flux.svg",
  minimax: "public/logos/minimax.svg",
  posterScroll: "public/screen/website-scroll.jpg",
  posterMouse: "public/screen/screen-mouse.jpg",
};

const mime = (p) => (p.endsWith(".svg") ? "image/svg+xml" : "image/jpeg");

let out = "// AUTO-GENERATED by scripts/gen_part1_assets.cjs — do not edit by hand.\n";
out += "export const ASSETS: Record<string, string> = {\n";
for (const [k, rel] of Object.entries(files)) {
  const buf = fs.readFileSync(path.join(ROOT, rel));
  const b64 = buf.toString("base64");
  const uri = `data:${mime(rel)};base64,${b64}`;
  out += `  ${k}: ${JSON.stringify(uri)},\n`;
}
out += "};\n";

fs.writeFileSync(path.join(ROOT, "src/scenes/motionFirst/part1Assets.ts"), out);
console.log("wrote part1Assets.ts with", Object.keys(files).length, "assets");
